spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    # Google smtp server
    host: smtp.gmail.com
    port: 587
    username: nakchoi94@gmail.com # Google ID
    password: wkwtisvcbzutpoli # Google App Password
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          ssl:
            trust: smtp.gmail.com
